"""The interface every memory-system adapter implements. The runner uses nothing else."""

from __future__ import annotations

from typing import Protocol

from erasewitness.scenario import Scenario
from erasewitness.types import Edge, EraseResult, Item, Layer


class Target(Protocol):
    name: str
    tested_versions: list[str]

    def setup(self, run_id: str) -> None: ...
    def version_info(self) -> dict[str, str]: ...
    def plant(self, text: str) -> None: ...
    def exercise(self, turns: list[str]) -> None: ...
    def settle(self, timeout_s: float) -> bool: ...
    def snapshot(self) -> list[Item]: ...
    def recorded_edges(self) -> list[Edge]: ...
    def erase(self, scenario: Scenario, strict_items: list[Item] | None) -> EraseResult: ...
    def probe_store(self, query: str) -> list[Item]: ...
    def probe_derived(self) -> list[Item]: ...
    def ask(self, question: str) -> str: ...
    def coverage(self) -> dict[Layer, bool]: ...
    def cleanup(self) -> list[str]: ...
